services:
  linkendin-post-cover:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.linkendin-post-cover.rule=Host(`lipg.interimu.nl`)"
      - "traefik.http.services.linkendin-post-cover.loadbalancer.server.port=3000"
      - "traefik.http.routers.linkendin-post-cover.tls=true"
      - "traefik.http.routers.linkendin-post-cover.tls.certresolver=myresolver"